import { createClient }from'@supabase/supabase-js'
const supabaseUrl = 'https://uvhumktctzhbmnoydfay.supabase.co'
const supabaseAnonKey = ' eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aHVta3RjdHpoYm1ub3lkZmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0ODgwMzQsImV4cCI6MjA5MDA2NDAzNH0.yZ_BlXVxN3D0WTqMCBO6XeOG4p7jYAX1ZcMIV1fCEGM'
export const supabase =createClient(supabaseUrl,supabaseAnonKey)